// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs99xfdilGS4sabWkx19RJ3BXqPfllByI',
    appId: '1:676612443237:web:53fea73f465627171e0a8c',
    messagingSenderId: '676612443237',
    projectId: 'safe-campus-iukl',
    authDomain: 'safe-campus-iukl.firebaseapp.com',
    storageBucket: 'safe-campus-iukl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6LVv3F_8Ekx2sSn8moX1eiVA6s4eemY',
    appId: '1:676612443237:android:05d0881cf093ccc31e0a8c',
    messagingSenderId: '676612443237',
    projectId: 'safe-campus-iukl',
    storageBucket: 'safe-campus-iukl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_nk0rqCpHm693gP8EILgwaing9Gd26Rs',
    appId: '1:676612443237:ios:3efef31625dbb9e71e0a8c',
    messagingSenderId: '676612443237',
    projectId: 'safe-campus-iukl',
    storageBucket: 'safe-campus-iukl.appspot.com',
    iosClientId: '676612443237-3fc8gt076itlbceo0k3u717obukunq1m.apps.googleusercontent.com',
    iosBundleId: 'com.digisailor.safecampus',
  );
}
